<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
use Mouf\MoufManager;
use Interop\Container\ContainerInterface;
MoufManager::initMoufManager();
$moufManager = MoufManager::getMoufManager();

$moufManager->getConfigManager()->setConstantsDefinitionArray(array (
));

$moufManager->setAllVariables(array (
));

$moufManager->addComponentInstances(array (
  '__anonymous__187718_1400490538467' => 
  array (
    'class' => 'Mouf\\Sample\\Axe',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
  ),
  '__anonymous__214772_1400489692580' => 
  array (
    'class' => 'Mouf\\Sample\\Axe',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
  ),
  '__anonymous__327470_1400490540218' => 
  array (
    'class' => 'Mouf\\Sample\\Axe',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
  ),
  '__anonymous__651817_1400489694186' => 
  array (
    'class' => 'Mouf\\Sample\\Sword',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
  ),
  'enemy' => 
  array (
    'class' => 'Mouf\\Sample\\Warrior',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '__anonymous__187718_1400490538467',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => '__anonymous__327470_1400490540218',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => '10',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'hero' => 
  array (
    'class' => 'Mouf\\Sample\\Warrior',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '__anonymous__214772_1400489692580',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => '__anonymous__651817_1400489694186',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => '30',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
));


unset($moufManager);

/**
 * This is the base class of the Manage Object User Friendly or Modular object user framework (MOUF) framework.
 * This object can be used to get the objects manage by MOUF.
 *
 */
class Mouf {
	public function getClosures() {
		return [
		];
	}
	/**
	 * @return Mouf\Sample\Warrior
	 */
	 public static function getEnemy() {
	 	return MoufManager::getMoufManager()->getInstance('enemy');
	 }

	/**
	 * @return Mouf\Sample\Warrior
	 */
	 public static function getHero() {
	 	return MoufManager::getMoufManager()->getInstance('hero');
	 }

}
?>
